CREATE DATABASE PIZZA_SALES_DB;
USE  PIZZA_SALES_DB;
SELECT * FROM PIZZA_SALES;

-- DATA ANALYSIS USING SQL
-- Total Revenue
SELECT SUM(total_price) AS Total_Revenue FROM pizza_sales;

--  Average Order Value
SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT(ORDER_ID)) FROM PIZZA_SALES;

--  Total Pizzas Sold
SELECT SUM(QUANTITY) FROM PIZZA_SALES;

-- Total Orders
SELECT COUNT(DISTINCT(ORDER_ID)) FROM PIZZA_SALES;

-- Average Pizzas Per Order
SELECT SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;

-- Daily Trend for Total Orders
SELECT DAYNAME(ORDER_DATE) AS ORDER_DATE, COUNT(DISTINCT ORDER_ID) AS COUNT_OF_ORDERS FROM PIZZA_SALES 
GROUP BY DAYNAME(ORDER_DATE);

-- Monthly Trend for Orders
SELECT MONTHNAME(ORDER_DATE) AS MONTHS, COUNT(DISTINCT ORDER_ID ) ORDERS FROM PIZZA_SALES 
GROUP BY MONTHNAME(ORDER_DATE);

-- % of Sales by Pizza Category
SELECT PIZZA_CATEGORY,ROUND(SUM(TOTAL_PRICE),2) AS TOTAL_SALES, 
ROUND(SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES 
WHERE MONTH(ORDER_DATE) = 1),2) AS PERCENTAGE_OF_SALES FROM PIZZA_SALES 
WHERE MONTH(ORDER_DATE) = 1 #FILTER AS NEEDED BASED TO MONTH
GROUP BY PIZZA_CATEGORY;

-- % of Sales by Pizza Size
SELECT PIZZA_SIZE,ROUND(SUM(TOTAL_PRICE),2) AS TOTAL_SALES, 
ROUND(SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) 
FROM PIZZA_SALES WHERE MONTH(ORDER_DATE) = 1),2) AS PERCENTAGE_OF_SALES FROM PIZZA_SALES 
WHERE MONTH(ORDER_DATE) = 1 #FILTER AS NEEDED BASED TO MONTH
GROUP BY PIZZA_SIZE;

SELECT PIZZA_SIZE,ROUND(SUM(TOTAL_PRICE),2) AS TOTAL_SALES, 
ROUND(SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES 
WHERE QUARTER(ORDER_DATE) = 1),2) AS PERCENTAGE_OF_SALES FROM PIZZA_SALES 
WHERE QUARTER(ORDER_DATE) = 1 #FILTER AS NEEDED BASED TO QUARTER
GROUP BY PIZZA_SIZE;

-- Top 5 Best selling pizzas
SELECT PIZZA_NAME,SUM(TOTAL_PRICE) FROM PIZZA_SALES 
GROUP BY PIZZA_NAME
ORDER BY SUM(TOTAL_PRICE) DESC
LIMIT 5;

-- Bottom 5 Pizzas by Revenue
SELECT PIZZA_NAME,SUM(TOTAL_PRICE) FROM PIZZA_SALES 
GROUP BY PIZZA_NAME
ORDER BY SUM(TOTAL_PRICE)
LIMIT 5;
 
-- Top 5 Pizzas by Quantity
SELECT PIZZA_NAME,SUM(QUANTITY) FROM PIZZA_SALES 
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) DESC
LIMIT 5;

-- Bottom 5 Pizzas by Quantity
SELECT PIZZA_NAME,SUM(QUANTITY) FROM PIZZA_SALES 
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) 
LIMIT 5;

